# Pengaturan Dasar Situs
title: FinFamily - Manajemen Keuangan Keluarga Modern
email: ishikawauta@eksashop.web.id
description: >-
  Solusi cerdas manajemen keuangan keluarga. Pantau pengeluaran, 
  pemasukan, dan tabungan dengan dasbor modern, aman, dan privat 
  dilengkapi fitur Smart OCR & Laporan Excel.
baseurl: ""
url: "https://finfamily-app.netlify.app"

# Informasi Penulis & Sosial
author:
  name: IshikawaUta
  github: IshikawaUta
twitter_username:

# Permalinks
permalink: /:title/

# Koleksi & Folder
include:
  - functions
  - .netlify
  - 404.html

# Pengaturan Build
markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pengaturan SEO & Metadata
lang: id-ID
timezone: Asia/Jakarta

# Exclude (File yang tidak perlu di-build menjadi website statis)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - .netlify/
  - .github/
  - deno.lock
  - .env
  - README.md