[build]
  publish = "_site"
  command = "bundle exec jekyll build"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "bundle exec jekyll serve --port 4000"
  port = 8888
  targetPort = 4000
  publish = "_site"